---
x-pg-host: &pghost huautla
x-pg-port: &pgport 5432
x-pg-user: &pguser postgres
x-pg-pass: &pgpass root
x-pg-ssl: &pgssl disable
x-api-host: &apihost cffc
x-api-port: &apiport 8080

services:

  postgres:
    image: jsmit257/huautla:lkg
    restart: always
    hostname: huautla
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: *pgpass

  run-docker:
    depends_on: [ postgres ]
    image: cffc:latest
    hostname: *apihost
    ports: [ 7998:8080 ]
    build: .
    volumes:
      - ./album:/album
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: *apihost
      HTTP_PORT: *apiport

  system-test:
    depends_on: [ run-docker ]
    image: golang:bookworm
    volumes: [ .:/cffc ]
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: *apihost
      HTTP_PORT: *apiport
    working_dir: /cffc
    command: ./bin/system-test.sh

  cffc-web:
    depends_on: [ run-docker ]
    image: cffc-web:latest
    restart: always
    hostname: cffc-web
    ports: [ 8080:80 ]
    volumes:
      - ./tests/data/:/www/css/images/background/
      - ./album:/album
    environment:
      CFFC_API_HOST: *apihost
      CFFC_API_PORT: *apiport
