---
version: "3.1"

x-pg-host: &pghost huautla
x-pg-port: &pgport 5432
x-pg-user: &pguser postgres
x-pg-pass: &pgpass root
x-pg-ssl: &pgssl disable

services:

  postgres:
    image: jsmit257/huautla:lkg
    restart: always
    hostname: huautla
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: *pgpass

  run-docker:
    depends_on: [ postgres ]
    image: cffc:latest
    hostname: cffc
    build: .
    ports: [ 8080:8080 ]
    volumes:
      - ./www/test-harness/css/images/background/:/www/test-harness/css/images/background/
      - ./photos:/photos
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: cffc
      HTTP_PORT: 8080

  system-test:
    depends_on: [ run-docker ]
    image: golang:bookworm
    volumes: [ .:/cffc ]
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: cffc
      HTTP_PORT: 8080
    working_dir: /cffc
    command: ./bin/system-test.sh
