---
version: "3.1"

x-pg-host: &pghost huautla
x-pg-port: &pgport 5432
x-pg-user: &pguser postgres
x-pg-pass: &pgpass root
x-pg-ssl: &pgssl disable

services:

  postgres:
    image: huautla:lkg
    restart: always
    hostname: huautla
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: *pgpass

  run-docker:
    depends_on: [ postgres ]
    image: cffc:test
    hostname: cffc
    build: .
    ports: [ 8081:8080 ]
    volumes: [ .:/go/src/github.com/jsmit257/huautla ]
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: cffc
      HTTP_PORT: 8080

  system-test:
    depends_on: [ postgres ]
    image: golang:bookworm
    volumes: [ .:/cffc ]
    environment:
      POSTGRES_HOST: *pghost
      POSTGRES_PORT: *pgport
      POSTGRES_USER: *pguser
      POSTGRES_PASSWORD: *pgpass
      POSTGRES_SSLMODE: *pgssl
    working_dir: /cffc
    command: ./bin/install-system-test.sh
