---
x-pg-host: &pghost huautla
x-pg-port: &pgport 5432
x-pg-user: &pguser postgres
x-pg-pass: &pgpass root
x-pg-ssl: &pgssl disable
x-api-host: &apihost cffc
x-api-port: &apiport 8080
x-usdb-host: &usdb-host usdb
x-usdb-port: &usdb-port 3306
x-usdb-user: &usdb-user root
x-usdb-pass: &usdb-pass root
x-usredis-host: &usredis-host usredis
x-usredis-port: &usredis-port 6379
x-ussrv-host: &ussrv-host ussrv
x-ussrv-port: &ussrv-port 80

services:

  postgres:
    image: jsmit257/huautla:lkg
    restart: always
    hostname: huautla
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: *pgpass

  us-authn:
    image: redis:bookworm
    restart: always
    hostname: *usredis-host

  us-db:
    image: jsmit257/us-db-mysql-test:lkg
    restart: always
    hostname: *usdb-host
    environment:
      MYSQL_ROOT_PASSWORD: *usdb-pass

  us-srv:
    depends_on:
      - us-authn
      - us-db
    image: jsmit257/us-srv-mysql:lkg
    hostname: *ussrv-host
    restart: always
    environment:
      US_MYSQL_HOST: *usdb-host
      US_MYSQL_PORT: *usdb-port
      US_MYSQL_USER: *usdb-user
      US_MYSQL_PASSWORD: *usdb-pass
      US_HTTP_HOST: *ussrv-host
      US_HTTP_PORT: *ussrv-port
      # US_REDIS_USER: *usredis-user
      # US_REDIS_PASS: *usredis-pass
      US_REDIS_HOST: *usredis-host
      US_REDIS_PORT: *usredis-port

  run-docker:
    depends_on:
      - postgres
      - us-srv
    image: jsmit257/cffc:latest
    hostname: *apihost
    restart: always
    ports: [ 7998:8080 ]
    build: .
    volumes:
      - ./testalbum:/album
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: *apihost
      HTTP_PORT: *apiport
      # AUTHN_HOST: *ussrv-host
      # AUTHN_PORT: *ussrv-port

  system-test:
    depends_on: [ run-docker ]
    image: golang:bookworm
    volumes: [ .:/cffc ]
    environment:
      HUAUTLA_HOST: *pghost
      HUAUTLA_PORT: *pgport
      HUAUTLA_USER: *pguser
      HUAUTLA_PASSWORD: *pgpass
      HUAUTLA_SSL: disable
      HTTP_HOST: *apihost
      HTTP_PORT: *apiport
    working_dir: /cffc
    command: ./bin/system-test.sh

  cffc-web:
    depends_on:
      - run-docker
      - us-srv # remove this when authn works in run-docker
    image: jsmit257/cffc-web:lkg
    restart: always
    hostname: cffc-web
    ports: [ 8080:80 ]
    volumes:
      - ./tests/data/:/www/css/images/background/
      - ./testalbum:/album
    environment:
      CFFC_API_HOST: *apihost
      CFFC_API_PORT: *apiport
      AUTHN_HOST: *ussrv-host
      AUTHN_PORT: *ussrv-port
